services:
  # database
  postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1
      
  # web
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 
    ports:
      - 8000:8000
    environment:
      - DB_HOST=postgresql
    volumes:
      - .:/code
    depends_on:
      - postgresql