name: Grocery Pull Request Check
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with ruff
        uses: chartboost/ruff-action@v1
      - name: Test with Django test
        run: |
          python manage.py test
      - name: Check migrations
        run: |
          python manage.py makemigrations --check --dry-run
      - name: Code coverage
        run: |
          coverage run --source='.' manage.py test
          coverage report --fail-under=80
