# Generated by Django 5.0.2 on 2024-03-12 08:43

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[products.models.non_negative_validator]),
        ),
    ]
